const performanceCycles = [
  {
    id: 0,
    name: "Annual Review 2025",
    type: "Annual Review",
    Year: "2025",
    status: "Active",
    startDate: new Date().toLocaleString(),
    endDate: new Date().toLocaleString(),
    participants: 9,
    progress: 80,
    // endDate: "15/23/2025",
  },
  {
    id: 1,
    name: "Annual Review 2023",
    type: "Annual Review",
    Year: "2023",
    status: "Active",
    startDate: new Date().toLocaleString(),
    endDate: new Date().toLocaleString(),
    participants: 11,
    // endDate: "15/23/2025",
    progress: 65,
  },
  {
    id: 3,
    name: "Annual Review 2024",
    type: "Mid-year Review",
    Year: "2024",
    status: "Completed",
    startDate: new Date().toLocaleString(),
    endDate: new Date().toLocaleString(),
    participants: 5,
    // endDate: "15/23/2025",
    progress: 50,
  },
  {
    id: 4,
    name: "Annual Review 2025",
    type: "Annual Review",
    Year: "2025",
    status: "Completed",
    startDate: new Date().toLocaleString(),
    endDate: new Date().toLocaleString(),
    // endDate: "15/23/2025",
    participants: 11,
    progress: 70,
  },
];

export default performanceCycles;
